mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapping/*.xml
  type-aliases-package: com.heyi.erciyuan.erciyuan.entity
  jpa:
    hibernate:
      #更新或者创建数据表结构
      ddl-auto: update
      #控制台显示sql语句
      show-sql: true
